#!/bin/bash

while true; do
    echo -e "\nMeniu:"
    echo "Tasta 1 ->> Inregistrare"
    echo "Tasta 2 ->> Autentificare"
    echo "Tasta 3 ->> Iesire din contr"
    echo "Tasta 4 ->> Schimbare parola"
    echo "Tasta 5 ->> Iesire din program "
    echo "Alegeți o opțiune:"
    read option

    case $option in
        1)
            source inregistrare_utilizator.sh  # Apelăm scriptul de înregistrare
            ;;
        2)
            ./autentificare_utilizator.sh  # Apelăm scriptul de autentificare
            ;;
        3)
            ./logout_utilizator.sh  # Apelăm scriptul de logout
            ;;
        4)
            ./modificare_parola.sh  # Apelăm scriptul de modificare a parolei
            ;;
        5)
            echo "Ieșire din program."
            break
            ;;
        *)
            echo "Opțiune invalidă. Vă rugăm să selectați din nou."
            ;;
    esac
done
